import { CategoryInfo } from '@/types';

export const PAGE_SIZE = 6;
export const USERS_PAGE_SIZE = 5;

export const categoryMetadata: Record<string, CategoryInfo> = {
	'beauty-and-spas': {
		name: 'Beauty & Spas',
		icon: '💄',
		description: 'Pamper yourself with spa treatments, massages, and beauty services',
		color: 'from-pink-500 to-rose-500',
	},
	'things-to-do': {
		name: 'Things To Do',
		icon: '🎯',
		description: 'Exciting activities, entertainment, and experiences',
		color: 'from-blue-500 to-cyan-500',
	},
	'health-and-fitness': {
		name: 'Health & Fitness',
		icon: '🎯',
		description: 'Exciting activities, entertainment, and experiences',
		color: 'from-blue-500 to-cyan-500',
	},
	'auto-and-home': {
		name: 'Auto & Home',
		icon: '🏠',
		description: 'Home improvement, automotive services, and maintenance',
		color: 'from-green-500 to-emerald-500',
	},
	'food-and-drink': {
		name: 'Food & Drink',
		icon: '🍕',
		description: 'Restaurants, cafes, bars, and culinary experiences',
		color: 'from-orange-500 to-red-500',
	},
	gifts: {
		name: 'Gifts',
		icon: '🎁',
		description: 'Perfect gifts for every occasion and special someone',
		color: 'from-purple-500 to-pink-500',
	},
	local: {
		name: 'Local',
		icon: '📍',
		description: 'Discover local businesses and community services',
		color: 'from-indigo-500 to-purple-500',
	},
	travel: {
		name: 'Travel',
		icon: '✈️',
		description: 'Hotels, flights, tours, and travel experiences',
		color: 'from-teal-500 to-blue-500',
	},
	goods: {
		name: 'Goods',
		icon: '🛍️',
		description: 'Shopping deals on products and merchandise',
		color: 'from-yellow-500 to-orange-500',
	},
	coupons: {
		name: 'Coupons',
		icon: '🎫',
		description: 'Digital coupons and promotional codes',
		color: 'from-red-500 to-pink-500',
	},
};

export const categories = [
	{ name: 'Beauty & Spas', icon: '💄' },
	{ name: 'Things To Do', icon: '🎯' },
	{ name: 'Auto & Home', icon: '🏠' },
	{ name: 'Food & Drink', icon: '🍽️' },
	{ name: 'Gifts', icon: '🎁' },
	{ name: 'Local', icon: '📍' },
	{ name: 'Travel', icon: '✈️' },
	{ name: 'Goods', icon: '🛍️' },
	{ name: 'Coupons', icon: '🎫' },
];

export const USA_LOCATIONS = [
	// Major Cities
	'New York, NY',
	'Los Angeles, CA',
	'Chicago, IL',
	'Houston, TX',
	'Phoenix, AZ',
	'Philadelphia, PA',
	'San Antonio, TX',
	'San Diego, CA',
	'Dallas, TX',
	'San Jose, CA',
	'Austin, TX',
	'Jacksonville, FL',
	'Fort Worth, TX',
	'Columbus, OH',
	'Charlotte, NC',
	'San Francisco, CA',
	'Indianapolis, IN',
	'Seattle, WA',
	'Denver, CO',
	'Washington, DC',
	'Boston, MA',
	'El Paso, TX',
	'Nashville, TN',
	'Detroit, MI',
	'Oklahoma City, OK',
	'Portland, OR',
	'Las Vegas, NV',
	'Memphis, TN',
	'Louisville, KY',
	'Baltimore, MD',
	'Milwaukee, WI',
	'Albuquerque, NM',
	'Tucson, AZ',
	'Fresno, CA',
	'Sacramento, CA',
	'Mesa, AZ',
	'Kansas City, MO',
	'Atlanta, GA',
	'Long Beach, CA',
	'Colorado Springs, CO',
	'Raleigh, NC',
	'Miami, FL',
	'Virginia Beach, VA',
	'Omaha, NE',
	'Oakland, CA',
	'Minneapolis, MN',
	'Tulsa, OK',
	'Arlington, TX',
	'Tampa, FL',
	'New Orleans, LA',

	// States for broader coverage
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming',
];
